# Generated by Django 4.2 on 2023-11-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board1',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('writer', models.CharField(blank=True, max_length=30, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('file1', models.CharField(blank=True, max_length=200, null=True)),
                ('boardid', models.CharField(blank=True, max_length=2, null=True)),
                ('regdate', models.DateTimeField(blank=True, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
                ('grp', models.IntegerField(blank=True, null=True)),
                ('grplevel', models.IntegerField(blank=True, null=True)),
                ('grpstep', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board1',
                'managed': False,
            },
        ),
    ]
